---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev2
  name: dev2-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev2
  name: dev2
  namespace: dev2-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev2
  name: dev2-reconciler
  namespace: dev2-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev2-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:dev2-ns:reconciler
- kind: ServiceAccount
  name: dev2
  namespace: dev2-ns

