---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev1-aspicot
  namespace: dev1-ns
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/one-kubernetes/dev1-aspicot-app/

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev1
  namespace: dev1-ns
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev1
  sourceRef:
    kind: GitRepository
    name: dev1-aspicot

